# -*- coding: utf-8 -*-
"""MAD-PAD_Actividad3_5M_20262.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mikxLngL32F3PrKuLCLoJF8RiUvecqTT

# Actividad 3. Análisis de retención de clientes con pandas

**Maestría en Analítica de Datos, Universidad Central**\
*Programación para Analítica de Datos*

**Modalidad:** individual  
**Duración máxima:** 45 minutos  
**Peso:** 15 %

**Nombre del estudiante:**

**Fecha:** *18-09-2026*

## Condiciones de desarrollo

La actividad se desarrolla de manera individual durante la sesión de clase. Se permite consultar los apuntes, presentaciones, guías y ejercicios trabajados previamente en el curso.

No se permite el uso de asistentes de inteligencia artificial, chatbots ni herramientas de generación automática de código durante la actividad. Quien tenga Visual Studio Code configurado con asistentes de autocompletado basados en inteligencia artificial deberá trabajar en Google Colab y mantener inhabilitadas las funciones de IA durante toda la actividad.

El notebook debe ejecutarse de principio a fin sin errores. Las decisiones tomadas durante el análisis deben poder ser explicadas por el estudiante.

## Situación

Una empresa de telecomunicaciones dispone de información histórica de sus clientes y requiere revisar algunos factores asociados con la cancelación del servicio.

El área de retención necesita comparar el comportamiento de los clientes según el tipo de contrato e identificar un grupo que, por sus condiciones de permanencia y facturación, debe ser revisado con mayor detalle.

El análisis debe realizarse únicamente con la información disponible en el archivo suministrado y los resultados deben presentarse de manera que puedan ser interpretados por el área de negocio.

## Fuente de datos

Utilice el archivo CSV disponible en la siguiente dirección:

`https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv`

Cargue la información directamente desde Internet utilizando pandas. No descargue previamente el archivo al equipo.
"""

# Desarrolle aquí la carga de los datos y las importaciones necesarias.
import numpy as np
import pandas as pd
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
dataini = pd.read_csv(url)
dataini.head()

"""## 1. Revisión inicial de la información

Revise la estructura del conjunto de datos antes de iniciar el análisis y determine cuáles variables son necesarias para responder la solicitud del área de retención.

Como evidencia de esta revisión, presente:

- el número de registros y variables del conjunto de datos;
- los nombres de las variables que utilizará en el análisis;
- los tipos de datos de estas variables.

No se requiere una exploración exhaustiva de todas las columnas ni realizar procesos de limpieza o tratamiento de valores faltantes.
"""

# Desarrolle aquí la revisión inicial de la información.
data = dataini.copy()
data.shape

data.columns

data.info()

"""Variables para dar solución a las necesidades que requiere la compañía, frente a la permanencia y facturación de sus clientes y encontrar un comportamiento clave:
**Customer ID**= La identificación del cliente, puede ser numérico o texto, para la tabla es una combinación mixta y la lee como texto
**Contract** =tipo texto, muestra los tipos de contratos que se disponen
**Chur**=la variable de permanencia o abandono del cliente al cumplir el periodo, tipo booleana.
**ternure** = antigüedad del cliente, puede ser parte importante para la solitud de la compañía, tipo de dato es entero, se supone que son meses, por el tamaño (1, 45, ..) de los datos
**paymentmethod** = el método de pago puede ser otra variable importante para definir la permanencia del cliente (facilidad a la hora de cancelar o pagar su servicio) tipo texto.
**MonthlyCharges** = la variación del consumo en el mes puede ser un indicador de permanencia. Se puede suponer que la cantidades mayores significa que el cliente está a gusto y está consumiendo los servicios(se puede manejar como suposición)

## 2. Comportamiento de la cancelación según el tipo de contrato

El área de retención quiere establecer si existen diferencias en la cancelación del servicio entre los tipos de contrato disponibles.

Construya una tabla resumen por tipo de contrato que permita comparar:

- el número de clientes;
- el porcentaje de clientes que cancelaron el servicio;
- el cargo mensual promedio.

El resultado debe quedar organizado de manera que permita identificar directamente cuál tipo de contrato presenta el mayor porcentaje de cancelación.
"""

# Desarrolle aquí el análisis por tipo de contrato.
# tabla general d elas tres variables
columnas = ['customerID', 'Contract','Churn', 'MonthlyCharges']
tabla_1 = data[columnas]
tabla_1.head()

data['Churn_porcentaje']=  np.where(data['Churn'] == 'Yes',1,0)

tabla_resumen_tipo_contrato = (data
    .groupby('Contract')
    .agg(
        clientes=('customerID', 'count'),
        porcentaje_cancelacion=('Churn_porcentaje', 'mean' ),
        cargo_mensual_promedio=('MonthlyCharges', 'mean')
    )
    .reset_index()
)

tabla_resumen_tipo_contrato['porcentaje_cancelacion'] = (tabla_resumen_tipo_contrato['porcentaje_cancelacion'] * 100).round(2)
tabla_resumen_tipo_contrato['cargo_mensual_promedio'] = tabla_resumen_tipo_contrato['cargo_mensual_promedio'].round(2)

tabla_resumen_tipo_contrato = tabla_resumen_tipo_contrato.sort_values('porcentaje_cancelacion', ascending=False)

tabla_resumen_tipo_contrato

"""## 3. Clientes para revisión prioritaria

Como parte de una revisión inicial, el área de retención quiere identificar clientes que continúan activos y que cumplen simultáneamente las siguientes condiciones:

- no han cancelado el servicio (`Churn = No`);
- tienen contrato mes a mes (`Month-to-month`);
- llevan 12 meses o menos con la empresa;
- presentan un cargo mensual (`MonthlyCharges`) superior a la mediana de esta variable en el conjunto de datos.

Construya un DataFrame con los clientes que cumplen estas condiciones y determine:

- cuántos clientes forman parte del grupo;
- cuál método de pago es el más frecuente;
- cuál es el cargo mensual promedio del grupo.

Conserve el DataFrame resultante para la revisión de la actividad.
"""

# Desarrolle aquí la identificación y el análisis del grupo de revisión prioritaria.
mediana_cargo = data['MonthlyCharges'].median()
mediana_cargo
mascara= (data['Churn'] == 'No') & (data['Contract'] == 'Month-to-month') & (data['tenure'] <= 12) & (data['MonthlyCharges'] > mediana_cargo)
columnas_importantes= ['customerID', 'PaymentMethod', 'MonthlyCharges']
clientes_prioritarios=data.loc [mascara, columnas_importantes]
print(clientes_prioritarios.head())
print("\nCantidad de clientes" , len(clientes_prioritarios))
print("\nResumen del mas frecuente en")
print((clientes_prioritarios['PaymentMethod'].value_counts()))
print("\nCargo mensual promedio", clientes_prioritarios['MonthlyCharges'].mean())

"""## 4. Conclusión para el área de retención

A partir de los resultados obtenidos, redacte una conclusión breve, de máximo 120 palabras, en la que responda:

1. ¿Qué tipo de contrato presenta el mayor porcentaje de cancelación?
2. ¿Qué diferencias relevantes observa en el cargo mensual promedio según el tipo de contrato?
3. ¿Cuántos clientes conforman el grupo definido para revisión prioritaria y cuál es el método de pago más frecuente?
4. A partir de los resultados calculados, ¿qué aspecto debería revisar primero el área de retención?

Las respuestas deben sustentarse en los valores obtenidos en el análisis. No se califican afirmaciones generales que no estén respaldadas por los resultados del notebook.

### Respuesta

Escriba aquí la conclusión.

El tipo de contrato con mayor tasa de cancelación es el mensual ("mes a mes"), registrando un 47.71% de deserción.Inicialmente, se planteó la hipótesis de que los clientes con mayor consumo mensual tendrían una mayor permanencia, bajo el supuesto de que un gasto alto reflejaba satisfacción con el servicio. Sin embargo, los resultados demostraron lo contrario: el contrato "mes a mes" presentó el cargo mensual promedio más alto, lo que refuta la teoría inicial. Por su parte, los clientes con contratos a largo plazo mostraron un consumo menor. Una explicación posible es que los usuarios con contratos mensuales necesitan utilizar los servicios al máximo durante un periodo corto y específico, para luego cancelarlos, lo que guarda una correlación directa con la alta tasa de abandono observada.El grupo definido para revisión prioritaria está conformado por 244 clientes, cuyo método de pago más frecuente es el cheque electrónico (Electronic check), representando el 64% del total (158 de los 244 usuarios).Para ofrecer una solución efectiva al área de retención, es necesario determinar si el valor de los servicios mensuales varía según el consumo o si se mantiene fijo dentro de ciertos límites. Esta definición es clave para diseñar la estrategia del área. Permitirá evaluar si es más conveniente enfocarse en los clientes de contrato mensual para migrarlos a planes de uno o más años —asegurando así un flujo constante de ingresos— o si, por el contrario, el esquema de consumo actual de los contratos "mes a mes" se alinea mejor con los costos operativos de la compañía.

## Criterios de evaluación

| Criterio | Peso |
|---|---:|
| Carga y revisión inicial de la información | 20 % |
| Análisis de cancelación por tipo de contrato | 35 % |
| Identificación y análisis del grupo de revisión prioritaria | 30 % |
| Interpretación de resultados y conclusión | 15 % |

La calificación considera tanto la corrección de los resultados como la coherencia del procedimiento utilizado. El profesor podrá solicitar la explicación o modificación de una parte del código desarrollado.
"""