# -*- coding: utf-8 -*-
"""Trabajo en clase 9.09.2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfK_uL6GSsyEVaCx1Bp0Jc_o00NmleGf
"""

def suma (a, b=10):
  return a +b

x = suma (5)
y=suma(5,2)
z=suma(b=1,a=1)

print(x,y,z)

def promedio(notas):
    total = 0
    for n in notas:
        total = total + n
    return total / len(notas)

def aprueba(prom):
    return prom >= 3.0

notas = [2.5, 3.2, 2.8]
prom = promedio(notas)

print("Promedio:", prom)
if aprueba(prom):
    print("Aprobado")
else:
    print("No aprobado")

# Notas de otra persona
notas_otra_persona = [4.0, 3.8, 4.5, 3.0]

prom_otra_persona = promedio(notas_otra_persona)

print(f"Promedio de otra persona: {prom_otra_persona:.2f}")
if aprueba(prom_otra_persona):
    print("Aprobado")
else:
    print("No aprobado")

def doble(n):
    return n * 2

x = doble(5)
print(x)

def perfil(nombre, edad, ciudad):
    print(nombre, edad, ciudad)

# Por posicion
perfil("Ana", 20, "Bogota")

# Por nombre (keyword)
perfil(edad=20, nombre="Ana", ciudad="Bogota")

# Mezcla: las posicionales primero
perfil("Ana", ciudad="Bogota", edad=20)

